/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author diniristanti
 */
public class buku extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public buku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        aa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idBuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        judul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        isbn = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        penulis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        penerbit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tahun = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        stock = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pokok = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jual = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        jTextField1.setFont(new java.awt.Font("Maiandra GD", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel10.setText("Data Buku Toko Buku \"Gradient\"");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199)
                .addComponent(jLabel10)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 0, 920, 100);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(null);

        delete.setText("Hapus");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(280, 30, 80, 40);

        save.setText("Simpan");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(10, 30, 70, 40);

        clear.setText("Bersihkan");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(90, 30, 90, 40);

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit);
        edit.setBounds(190, 30, 80, 40);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Buku", "Judul", "No ISBN", "Penulis", "Penerbit", "Tahun", "Stock", "Harga Pokok", "Harga Jual"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(3).setResizable(false);
            tabel.getColumnModel().getColumn(4).setResizable(false);
            tabel.getColumnModel().getColumn(5).setResizable(false);
            tabel.getColumnModel().getColumn(6).setResizable(false);
            tabel.getColumnModel().getColumn(8).setResizable(false);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 660, 402);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh);
        refresh.setBounds(370, 30, 80, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(240, 90, 680, 570);

        aa.setBackground(new java.awt.Color(204, 204, 204));
        aa.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel1.setText("Id Buku");
        aa.add(jLabel1);
        jLabel1.setBounds(10, 11, 80, 30);
        aa.add(idBuku);
        idBuku.setBounds(10, 40, 220, 30);

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel2.setText("Judul");
        aa.add(jLabel2);
        jLabel2.setBounds(10, 70, 80, 30);
        aa.add(judul);
        judul.setBounds(10, 100, 220, 30);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel3.setText("No ISBN");
        aa.add(jLabel3);
        jLabel3.setBounds(10, 130, 80, 30);
        aa.add(isbn);
        isbn.setBounds(10, 160, 220, 30);

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel4.setText("Penulis");
        aa.add(jLabel4);
        jLabel4.setBounds(10, 190, 80, 30);
        aa.add(penulis);
        penulis.setBounds(10, 220, 220, 30);

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel5.setText("Penerbit");
        aa.add(jLabel5);
        jLabel5.setBounds(10, 250, 80, 30);
        aa.add(penerbit);
        penerbit.setBounds(10, 280, 220, 30);

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel6.setText("Tahun");
        aa.add(jLabel6);
        jLabel6.setBounds(10, 310, 80, 30);
        aa.add(tahun);
        tahun.setBounds(10, 340, 220, 30);

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel7.setText("Stock");
        aa.add(jLabel7);
        jLabel7.setBounds(10, 370, 80, 30);
        aa.add(stock);
        stock.setBounds(10, 400, 220, 30);

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel8.setText("Harga Pokok");
        aa.add(jLabel8);
        jLabel8.setBounds(10, 430, 80, 30);
        aa.add(pokok);
        pokok.setBounds(10, 460, 220, 30);

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 0, 13)); // NOI18N
        jLabel9.setText("Harga Jual");
        aa.add(jLabel9);
        jLabel9.setBounds(10, 490, 80, 30);

        jual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jualActionPerformed(evt);
            }
        });
        aa.add(jual);
        jual.setBounds(10, 520, 220, 30);

        getContentPane().add(aa);
        aa.setBounds(0, 100, 240, 560);

        setBounds(0, 0, 936, 698);
    }// </editor-fold>//GEN-END:initComponents

    private void jualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jualActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if (idBuku.getText().equals("")|| judul.getText().equals("")|| isbn.getText().equals("")|| 
            penulis.getText().equals("")|| penerbit.getText().equals("")|| tahun.getText().equals("") || 
            stock.getText().equals("")|| pokok.getText().equals("")|| jual.getText().equals("")) {
           JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else{
            String SQL = "INSERT INTO buku VALUES" + "('"+idBuku.getText()+"','"+judul.getText()+"','"+isbn.getText()+"''"
                    +penulis.getText()+"','"+penerbit.getText()+"','"+tahun.getText()+"','"+stock.getText()+"','"+pokok.getText()
                    +"','"+jual.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        idBuku.setText("");
        judul.setText("");
        isbn.setText("");
        penulis.setText("");
        penerbit.setText("");
        tahun.setText("");
        stock.setText("");
        pokok.setText("");
        jual.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        if ("".equals(idBuku.getText()) || "".equals(judul.getText()) || "".equals(isbn.getText()) || "".equals(penulis.getText()) 
                || "".equals(penerbit.getText()) || "".equals(tahun.getText()) || "".equals(stock.getText()) 
                || "".equals(pokok.getText()) || "".equals(jual.getText()) ) {
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
        } else {
        String SQL = "UPDATE buku SET "
                + "Id Buku='"+idBuku.getText()+"',"
                +"Judul='"+judul.getText()+"',"
                + "No ISBN='"+isbn.getText()+"',"
                + "Penulis='"+penulis.getText()+"',"
                + "Penerbit='"+penerbit.getText()+"',"
                + "Tahun='"+tahun.getText()+"',"
                + "Stock='"+stock.getText()+"',"
                + "Harga Pokok='"+pokok.getText()+"',"
                + "Harga Jual='"+jual.getText()+"',"
                + "WHERE Id Buku='"+idBuku.getText()+"',";;
        int status = KoneksiDB.execute(SQL);
        if (status == 0) {
            JOptionPane.showMessageDialog(this, "Data Berhasil Update","Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        } else {
            JOptionPane.showMessageDialog(this, "Data Gagal Diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
     }
    }//GEN-LAST:event_editActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();
        if (baris != -1) {
            String idbuku = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM buku WHERE id_buku='"+idbuku+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }   
        } else {
            JOptionPane.showMessageDialog(this,"Pilih Baris Data Terlebih Dahulu","Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_refreshActionPerformed
    
    private void selectData() {
        String kolom[] = {"Id Buku", "Judul", "No ISBN","Penulis","Penerbit", "Tahun", "Stock", "Harga Pokok", "Harga Jual"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM buku";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
        while(rs.next()){
            String IdBuku       = rs.getString(1);
            String Judul        = rs.getString(2);
            String ISBN         = rs.getString(3);
            String Penulis      = rs.getString(4);
            String Penerbit     = rs.getString(5);
            String Tahun        = rs.getString(6);
            String Stock        = rs.getString(7);
            String HargaPokok   = rs.getString(8);
            String HargaJual    = rs.getString(9);
            String data[] = {IdBuku,Judul,ISBN,Penulis,Penerbit,Tahun,Stock,HargaPokok,HargaJual};
            dtm.addRow(data);
        }
        
        }catch(SQLException ex){
            Logger.getLogger(buku.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(dtm);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aa;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField idBuku;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jual;
    private javax.swing.JTextField judul;
    private javax.swing.JTextField penerbit;
    private javax.swing.JTextField penulis;
    private javax.swing.JTextField pokok;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTextField stock;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tahun;
    // End of variables declaration//GEN-END:variables

}
